# Generated by Django 6.0.1 on 2026-02-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0003_add_card_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='stock_investment',
            field=models.IntegerField(default=0),
        ),
    ]
