# Generated by Django 6.0.1 on 2026-02-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0005_evolution_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchoice',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_engine.choice'),
        ),
    ]
