# Generated by Django 6.0.1 on 2026-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0007_gamesession_market_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='highest_credit_score',
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='highest_happiness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='highest_stock_profit',
            field=models.IntegerField(default=0),
        ),
    ]
