# Generated by Django 6.0.1 on 2026-02-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0009_gamesession_purchase_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('units', models.FloatField()),
                ('strike_price', models.IntegerField()),
                ('spot_price_at_sale', models.IntegerField()),
                ('duration_months', models.IntegerField()),
                ('created_month', models.IntegerField()),
                ('final_market_price', models.IntegerField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_contracts', to='game_engine.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('price', models.IntegerField()),
                ('volatility_index', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_history', to='game_engine.gamesession')),
            ],
            options={
                'ordering': ['session', 'month'],
                'unique_together': {('session', 'sector', 'month')},
            },
        ),
    ]
