# Generated by Django 6.0.1 on 2026-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0010_futurescontract_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('LIFESTYLE', 'Lifestyle'), ('DEBT', 'Debt & Loans'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='inflation_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
