# Generated by Django 6.0.1 on 2026-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0011_recurringexpense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='feedback_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='feedback_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_mr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
