# Generated by Django 6.0.1 on 2026-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0015_gamesession_active_ipos_gamesession_mutual_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('rsi', models.FloatField()),
                ('macd', models.FloatField()),
                ('signal', models.FloatField()),
                ('daily_return', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='game_engine_ticker_1ad959_idx')],
            },
        ),
    ]
